/* entidad.js — módulo "Mi entidad": datos internos del SIAF de una entidad, cifrados; se abren solo con su clave.
   Depende de helpers globales de index.html: $, j, M, N, P, cls, toast, UES, ficha(), ANIO, R. */
(function () {
  const F = n => n == null ? '—' : 'S/ ' + Number(n).toLocaleString('es-PE', { maximumFractionDigits: 0 });
  const FASE = { C: 'Compromiso', D: 'Devengado', G: 'Girado', P: 'Pagado', R: 'Rendición' };
  let E = null, META = {}, LAKE = {}, tabE = 'res', filtroMeta = '', q = '', modoInv = true, abierto = null;
  const b64 = s => Uint8Array.from(atob(s), c => c.charCodeAt(0));

  async function descifrar(ue, clave) {
    const p = await j(`data/entidad/${ue}.enc`);
    const km = await crypto.subtle.importKey('raw', new TextEncoder().encode(clave), 'PBKDF2', false, ['deriveKey']);
    const key = await crypto.subtle.deriveKey({ name: 'PBKDF2', salt: b64(p.salt), iterations: p.iter, hash: 'SHA-256' }, km, { name: 'AES-GCM', length: 256 }, false, ['decrypt']);
    const pt = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: b64(p.iv) }, key, b64(p.data));
    const txt = await new Response(new Blob([pt]).stream().pipeThrough(new DecompressionStream('deflate'))).text();
    return JSON.parse(txt);
  }

  async function login() {
    const el = $('ent'); let lista = [];
    try { lista = await j('data/entidad/index.json'); } catch (e) { }
    el.innerHTML = `<div class="card" style="flex:0 0 auto;max-width:560px;margin:30px auto;padding:0"><div class="pd-hdr"><div class="pd-cui">MI ENTIDAD · ACCESO PRIVADO</div><div class="pd-title">Seguimiento interno con datos del SIAF</div><div class="pd-badges"><span class="pd-badge">Cifrado AES-256</span><span class="pd-badge">La clave nunca sale de tu navegador</span></div></div>
     <div style="padding:16px 18px"><p style="margin:0 0 10px;font-size:12.5px;color:var(--ink2)">Aquí la entidad ve lo que Transparencia no muestra: expediente por expediente, proveedor, documento, glosa y la fase en que está cada pago. La información es de la entidad: se publica cifrada y solo se abre con su clave.</p>
     ${lista.length ? `<label class="mutx" style="font-size:11px">Entidad</label><select id="ent-ue" style="width:100%;margin:4px 0 10px">${lista.map(x => `<option value="${x.ue}">${x.nombre || 'UE ' + x.ue} · SIAF al ${x.corte || ''}</option>`).join('')}</select>` : '<p class="mutx">Aún no hay entidades publicadas.</p>'}
     <label class="mutx" style="font-size:11px">Clave de acceso</label><input type="password" id="ent-clave" style="width:100%;padding:8px 10px;border:1.5px solid var(--line);border-radius:8px;font:inherit;margin:4px 0 12px" placeholder="••••••••" autocomplete="current-password">
     <div style="display:flex;gap:8px;align-items:center"><button class="btn p" id="ent-ir">Entrar</button><span class="mutx" id="ent-msg" style="font-size:12px"></span></div></div></div>`;
    const ir = async () => { const ue = $('ent-ue')?.value, clave = $('ent-clave').value; if (!ue || !clave) return; $('ent-msg').textContent = 'Descifrando…';
      try { E = await descifrar(ue, clave); await preparar(ue); render(); } catch (e) { console.warn(e); $('ent-msg').textContent = 'Clave incorrecta o archivo no disponible.'; } };
    $('ent-ir').onclick = ir; $('ent-clave').onkeydown = e => { if (e.key === 'Enter') ir(); }; $('ent-clave').focus();
  }

  async function preparar(ue) {
    META = {}; E.metas.forEach(m => META[m.sec_func] = m);
    const uf = await ficha(ue).catch(() => null); LAKE = {}; (uf?.cuis || []).forEach(c => LAKE[c.cui] = c); E._ue = UES.find(u => u.cod === ue) || { cod: ue, nombre: 'UE ' + ue }; E._uf = uf;
  }
  const inv = () => E.metas.filter(m => m.es_inv);
  const metasSel = () => modoInv ? inv() : E.metas;
  function tot() { const o = { cert: 0, comp: 0, dev: 0, gir: 0, pag: 0 }; metasSel().forEach(m => { for (const k in o) o[k] += m[k] || 0; }); o.pim = modoInv ? Object.values(LAKE).reduce((s, c) => s + (c.pim || 0), 0) : (E._uf?.pim_total || 0); return o; }
  function nombreMeta(m) { const c = LAKE[m.act_proy]; return c?.nombre || m.nombre_ap || m.nombre || `${m.act_proy} · meta ${m.meta}`; }

  const SW = (k, lbl, c) => `<div class="pd-kpi"><i style="background:${c}"></i><div class="l">${lbl}</div><div class="v">${M(k)} <small style="font-size:10px">M</small></div></div>`;
  const pila = []; let restaurando = false;
  function render() {
    if (!restaurando) { const cur = [tabE, filtroMeta, modoInv, q].join('|'); if (pila[pila.length - 1] !== cur) pila.push(cur); }
    restaurando = false;
    const el = $('ent'), u = E._ue, P_ = E.presupuesto, I = E.ingresos, T = modoInv ? P_.inversiones : P_.total, nAl = E.alertas.dev_sin_girar.length + E.alertas.comp_sin_devengar.length + E.alertas.cert_sin_comp.length;
    const tabs = [['res', 'Resumen'], ['ppto', 'Presupuesto'], ['inv', modoInv ? 'Inversiones' : 'Metas'], ['exp', 'Expedientes' + (filtroMeta ? ' · ' + filtroMeta : '')], ['ing', 'Ingresos'], ['pi', '🏅 Incentivos Municipales'], ['al', `Alertas (${nAl})`], ['prov', 'Proveedores'], ['cert', 'Certificaciones']];
    el.innerHTML = `<div class="card" style="flex:0 0 auto;padding:0"><div class="pd-hdr" style="border-radius:var(--rad)"><div class="pd-cui"><span>MI ENTIDAD · UE ${u.cod}</span><span>· SIAF al ${E.corte}</span><span>· Transparencia al ${R.corte}</span><span class="x" id="ent-salir" title="Cerrar sesión">×</span></div><div class="pd-title">${u.nombre}</div>
      <div class="pd-badges"><span class="pd-badge">${N(E.expedientes.length)} expedientes</span><span class="pd-badge">${N(inv().length)} inversiones · ${N(E.metas.length)} metas</span><span class="pd-badge">${N(E.modificaciones.length)} modificaciones presupuestales</span><span class="pd-badge ${nAl ? 'bad' : 'ok'}">${N(nAl)} alertas</span>
      <span class="sw" style="margin-left:auto"><button class="${modoInv ? 'on' : ''}" data-m="1">Solo inversiones</button><button class="${modoInv ? '' : 'on'}" data-m="0">Todo el gasto</button></span></div></div>
      <div class="pd-kpis">${SW(T.pim, 'PIM ' + ANIO, 'var(--gold)')}${SW(T.cert, 'Certificado', 'var(--p2)')}${SW(T.comp, 'Comprometido', 'var(--p)')}${SW(T.dev, 'Devengado', 'var(--ok)')}${SW(T.gir, 'Girado', 'var(--teal)')}${SW(T.pag, 'Pagado', '#5E35B1')}<div class="pd-kpi"><i style="background:var(--${cls(100 * T.dev / (T.pim || 1))})"></i><div class="l">Avance dev / PIM</div><div class="v" style="color:var(--${cls(100 * T.dev / (T.pim || 1))})">${(100 * T.dev / (T.pim || 1)).toFixed(1)} %</div></div></div>${(() => { const h = E._uf; if (!h || !h.pim) return ''; const dl = (h.dev || 0) - (P_.inversiones.dev || 0); return `<div style="display:flex;gap:18px;align-items:center;padding:6px 16px;background:linear-gradient(90deg,#E8F4FD,#F4F9FE);border-top:1px solid var(--grid);font-size:11.5px;flex-wrap:wrap"><b style="color:var(--p2)">HOY · inversiones según Transparencia (${R.corte.slice(0, 10)})</b><span>PIM <b>${M(h.pim)} M</b></span><span>Certificado <b>${M(h.cert)} M</b></span><span>Comprometido <b>${M(h.comp)} M</b></span><span>Devengado <b>${M(h.dev)} M</b></span><span>Girado <b>${M(h.gir)} M</b></span><span>Avance <b style="color:var(--${cls(100 * h.dev / h.pim)})">${P(100 * h.dev / h.pim)}</b></span>${dl > 1000 ? `<span style="color:var(--ok);font-weight:600">▲ ${M(dl)} M devengados desde el backup SIAF (${E.corte})</span>` : ''}<span class="mutx" style="margin-left:auto">el detalle por expediente/proveedor se actualiza con el respaldo SIAF</span></div>`; })()}</div>
     <div class="card" style="flex:1;min-height:0"><div class="ptabs">${tabs.map(([k, t]) => `<button class="${tabE === k ? 'on' : ''}" data-t="${k}">${t}</button>`).join('')}<button class="btn" id="ent-xls" style="margin-left:auto">⬇ Excel</button></div>
      <div class="filt" ${['res', 'ppto', 'ing', 'pi'].includes(tabE) ? 'hidden' : ''}><input type="search" id="ent-q" placeholder="Buscar en glosas, proveedores, documentos, CUI…" value="${q}"></div><div class="wrap" id="ent-body"></div></div>`;
    el.querySelectorAll('.ptabs button[data-t]').forEach(b => b.onclick = () => { tabE = b.dataset.t; if (tabE !== 'exp') filtroMeta = ''; render(); });
    el.querySelectorAll('.sw button').forEach(b => b.onclick = () => { modoInv = b.dataset.m === '1'; filtroMeta = ''; render(); });
    if ($('ent-q')) $('ent-q').oninput = e => { q = e.target.value.trim().toLowerCase(); cuerpo(); }; $('ent-salir').onclick = () => { E = null; login(); };
    $('ent-xls').onclick = () => { const rows = [...$('ent-body').querySelectorAll('tr:not(.det)')].map(tr => [...tr.children].map(td => td.innerText.replace(/\n/g, ' ').trim())); const ws = XLSX.utils.aoa_to_sheet(rows); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'MiEntidad'); XLSX.writeFile(wb, `mi_entidad_${u.cod}_${tabE}.xlsx`); };
    cuerpo();
  }
  const hit = (s) => !q || (s || '').toLowerCase().includes(q);
  const sec = (t, d) => `<div class="pd-lbl" style="margin:14px 8px 6px">${t}${d ? `<small>${d}</small>` : ''}</div>`;
  const barra = (v, max, col) => `<span class="bar" style="width:${Math.round(120 * Math.min(1, (v || 0) / (max || 1)))}px;background:${col || 'var(--p)'}"></span>`;
  // ponytail: un solo patrón para todas las pestañas — paneles resumen, clic = detalle en el mismo panel, clic otra vez = resumen
  const abiertos = {};
  function paneles(b, items, nota) {
    const ab = abiertos[tabE];
    b.innerHTML = `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:10px;padding:8px">${items.map(it => { const on = ab === it.id, col = it.color || 'var(--p)'; return `<div class="card pnl" data-p="${it.id}" style="flex:none;cursor:pointer;padding:0;border-left:5px solid ${col};${on ? 'grid-column:1 / -1;box-shadow:0 4px 18px rgba(15,42,67,.14)' : ''};background:${on ? '#fff' : `linear-gradient(135deg,#fff 55%,${it.bg || '#F4F8FC'})`}">
        <div style="display:flex;align-items:flex-start;gap:12px;padding:12px 14px"><div style="font-size:24px;line-height:1.2">${it.icono || ''}</div><div style="flex:1;min-width:0"><div class="pd-lbl" style="margin:0">${it.titulo}</div><div style="font-size:18px;font-weight:700;color:${col};margin:2px 0;line-height:1.25">${it.valor}</div><div class="mutx" style="font-size:11px;white-space:normal">${it.sub || ''}</div></div>${it.medidor != null ? `<div style="width:56px;height:56px;border-radius:50%;background:conic-gradient(${col} ${Math.min(100, it.medidor)}%,var(--grid) 0);display:grid;place-items:center;flex:none"><div style="width:42px;height:42px;border-radius:50%;background:#fff;display:grid;place-items:center;font-size:11px;font-weight:700;color:${col}">${Math.round(it.medidor)}%</div></div>` : ''}<div class="mutx" style="font-size:16px">${on ? '▲' : '▼'}</div></div>
        ${on ? `<div class="pnl-det" style="border-top:1px solid var(--grid);padding:6px 10px 10px;cursor:default">${it.detalle()}</div>` : ''}</div>`; }).join('')}</div>${nota ? `<p class="mutx" style="font-size:11px;padding:0 16px 8px">${nota}</p>` : ''}`;
    b.querySelectorAll('.pnl').forEach(c => c.onclick = e => { if (e.target.closest('.pnl-det')) return; const id = c.dataset.p; abiertos[tabE] = abiertos[tabE] === id ? null : id; cuerpo(); if (abiertos[tabE]) b.querySelector(`.pnl[data-p="${id}"]`)?.scrollIntoView({ block: 'start', behavior: 'smooth' }); });
  }
  const cap = t => { t = (t || '').replace(/^[\d.\s-]+/, '').toLowerCase(); t = t.charAt(0).toUpperCase() + t.slice(1); return t.length > 34 ? t.slice(0, 32) + '…' : t; };
  const FM = n => 'S/ ' + M(n) + ' M';
  const mlabel = s => META[s] ? (META[s].es_inv ? META[s].act_proy : 'meta ' + META[s].meta) : s;
  function cuerpo() {
    const b = $('ent-body'), P_ = E.presupuesto, I = E.ingresos, T = modoInv ? P_.inversiones : P_.total, A = E.alertas;
    const pct = (a, c) => 100 * (a || 0) / (c || 1);
    if (tabE === 'res') {
      const cad = [['PIM', T.pim, 'lo que puede gastar este año', 'var(--gold)'], ['Certificado', T.cert, 'presupuesto ya reservado para un gasto concreto', 'var(--p2)'], ['Compromiso anual', T.comp_anual, 'contratos y órdenes firmados por su valor total del año', 'var(--p)'], ['Comprometido', T.comp, 'la parte de esos contratos ya registrada para pagar', 'var(--p)'], ['Devengado', T.dev, 'bien o servicio recibido: deuda reconocida', 'var(--ok)'], ['Girado', T.gir, 'cheque o transferencia emitida', 'var(--teal)'], ['Pagado', T.pag, 'dinero que ya salió de la cuenta', '#5E35B1']];
      const fts = Object.values(P_.fuentes).filter(f => f.pim > 0).sort((a, c) => c.pim - a.pim);
      const top = inv().filter(m => m.pim > 0).sort((a, c) => c.pim - a.pim).slice(0, 10);
      const nAl = A.dev_sin_girar.length + A.comp_sin_devengar.length + A.cert_sin_comp.length, mAl = [...A.dev_sin_girar, ...A.comp_sin_devengar, ...A.cert_sin_comp].reduce((s, x) => s + (x.monto || 0), 0);
      paneles(b, [
        { id: 'flujo', icono: '💧', titulo: '¿Cuánto entra y cuánto sale?', valor: `${FM(I.total.recaudado)} entran · ${FM(P_.total.dev)} salen`, sub: `recaudado vs devengado ${ANIO} · ingresos al ${P(pct(I.total.recaudado, I.total.pim))} de su PIM`, color: 'var(--teal)', medidor: pct(P_.total.dev, P_.total.pim),
          detalle: () => `<table class="pd-tbl"><tr><th></th><th>Presupuesto (PIM)</th><th>Ejecutado</th><th>Avance</th></tr><tr><td>Ingresos recaudados</td><td>${F(I.total.pim)}</td><td>${F(I.total.recaudado)}</td><td>${P(pct(I.total.recaudado, I.total.pim))}</td></tr><tr><td>Gastos devengados</td><td>${F(P_.total.pim)}</td><td>${F(P_.total.dev)}</td><td>${P(pct(P_.total.dev, P_.total.pim))}</td></tr><tr><td>Gastos pagados</td><td></td><td>${F(P_.total.pag)}</td><td>${P(pct(P_.total.pag, P_.total.pim))}</td></tr><tr><td><b>Inversiones devengadas</b></td><td>${F(P_.inversiones.pim)}</td><td>${F(P_.inversiones.dev)}</td><td>${P(pct(P_.inversiones.dev, P_.inversiones.pim))}</td></tr></table>` },
        { id: 'cadena', icono: '⛓', titulo: 'La cadena del gasto', valor: `${P(pct(T.dev, T.pim))} devengado`, sub: `${modoInv ? 'solo inversiones' : 'todo el gasto'} · certificado ${P(pct(T.cert, T.pim))} · pagado ${P(pct(T.pag, T.pim))}`, color: 'var(--ok)', medidor: pct(T.dev, T.pim),
          detalle: () => `<table class="pd-tbl">${cad.map(([k, v, d, c]) => `<tr><td style="width:130px"><b>${k}</b></td><td style="width:140px">${barra(v, T.pim, c)}</td><td style="width:110px">${F(v)}</td><td class="mutx" style="text-align:left;font-size:10.5px">${d}</td></tr>`).join('')}</table>` },
        { id: 'alertas', icono: '🚨', titulo: 'Alertas que requieren decisión', valor: `${N(nAl)} casos · ${FM(mAl)}`, sub: `en pagos trabados, contratos sin avanzar y presupuesto inmovilizado`, color: nAl ? 'var(--bad)' : 'var(--ok)', bg: nAl ? '#FDECEC' : '#EAF5EA',
          detalle: () => `<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px">${[['dev_sin_girar', 'Proveedores sin cobrar', 'devengado sin girar > 15 días', 'bad'], ['comp_sin_devengar', 'Contratos sin avanzar', 'comprometido sin devengar > 45 días', 'warn'], ['cert_sin_comp', 'Presupuesto reservado sin usar', 'certificaciones > 60 días sin compromiso', 'p']].map(([k, t, d, c]) => `<div class="al ${c}" data-a="${k}" style="padding:8px 10px;cursor:pointer"><div class="n" style="font-size:20px">${A[k].length}</div><div class="t"><b>${t}</b><br>${d}</div></div>`).join('')}</div><p class="mutx" style="font-size:11px;margin:6px 0 0">Clic en un bloque para ver los casos.</p>` },
        { id: 'fuentes', icono: '🏦', titulo: '¿De dónde sale el dinero?', valor: fts[0] ? cap(fts[0].nombre) : '—', sub: `${fts.length} fuentes · la principal aporta ${P(pct(fts[0]?.pim, P_.total.pim))} del PIM`, color: 'var(--gold)',
          detalle: () => `<table class="pd-tbl"><tr><th>Fuente</th><th>PIM gasto</th><th>Devengado</th><th>Avance</th><th>Recaudado</th></tr>${fts.map(f => { const ing = Object.values(I.fuentes).find(x => x.nombre === f.nombre); return `<tr><td style="white-space:normal">${f.nombre}</td><td>${F(f.pim)}</td><td>${F(f.dev)}</td><td>${P(pct(f.dev, f.pim))}</td><td>${ing ? F(ing.recaudado) : '—'}</td></tr>`; }).join('')}</table>` },
        { id: 'top', icono: '🏗', titulo: 'Las 10 inversiones más grandes', valor: FM(top.reduce((s, m) => s + m.pim, 0)), sub: `${P(pct(top.reduce((s, m) => s + m.pim, 0), P_.inversiones.pim))} del PIM de inversiones · avance ${P(pct(top.reduce((s, m) => s + m.dev, 0), top.reduce((s, m) => s + m.pim, 0)))}`, color: 'var(--p2)',
          detalle: () => `<table class="pd-tbl"><tr><th>Inversión</th><th>PIM</th><th>Devengado</th><th>Avance</th></tr>${top.map(m => `<tr class="l" data-sf="${m.sec_func}" style="cursor:pointer"><td style="white-space:normal"><b>${m.act_proy}</b> ${nombreMeta(m).slice(0, 90)}</td><td>${F(m.pim)}</td><td>${F(m.dev)}</td><td>${P(pct(m.dev, m.pim))}</td></tr>`).join('')}</table>` }
      ], 'Clic en un panel para abrir su detalle; otro clic lo vuelve a cerrar.');
      b.querySelectorAll('.al').forEach(a => a.onclick = () => { tabE = 'al'; abiertos.al = a.dataset.a; render(); }); b.querySelectorAll('tr.l').forEach(tr => tr.onclick = () => { filtroMeta = tr.dataset.sf; tabE = 'exp'; render(); });
    } else if (tabE === 'ppto') {
      const fila = (n, d) => `<tr><td style="white-space:normal">${n}</td><td>${F(d.pia)}</td><td>${F(d.ampl + d.modif)}</td><td><b>${F(d.pim)}</b></td><td>${F(d.cert)}</td><td>${F(d.comp_anual)}</td><td>${F(d.dev)}</td><td>${F(d.gir)}</td><td>${F(d.pag)}</td><td>${P(pct(d.dev, d.pim))}</td></tr>`;
      const head = '<tr><th>Concepto</th><th>PIA</th><th>Modificaciones</th><th>PIM</th><th>Certificado</th><th>Compromiso anual</th><th>Devengado</th><th>Girado</th><th>Pagado</th><th>Avance</th></tr>';
      const mods = E.modificaciones.slice().reverse(), fts = Object.values(P_.fuentes).filter(f => f.pim).sort((a, c) => c.pim - a.pim), gen = Object.values(P_.genericas).filter(f => f.pim).sort((a, c) => c.pim - a.pim), pca = E.pca.filter(p => p.asignado);
      const pcaA = pca.reduce((s, p) => s + p.asignado, 0), pcaC = pca.reduce((s, p) => s + p.certificado, 0), cred = mods.reduce((s, m) => s + (m.credito || 0), 0);
      paneles(b, [
        { id: 'marco', icono: '📊', titulo: 'Marco presupuestal (todo el gasto)', valor: FM(P_.total.pim), sub: `PIM = PIA ${F(P_.total.pia)} + modificaciones ${F(P_.total.ampl + P_.total.modif)} · devengado ${P(pct(P_.total.dev, P_.total.pim))}`, color: 'var(--gold)', medidor: pct(P_.total.dev, P_.total.pim),
          detalle: () => sec('Por fuente de financiamiento', 'PIM = PIA + créditos suplementarios/transferencias + modificaciones') + `<table class="pd-tbl">${head}${fts.map(f => fila(f.nombre, f)).join('')}${fila('<b>Total</b>', P_.total)}</table>` },
        { id: 'gen', icono: '🧩', titulo: 'Por genérica de gasto', valor: gen[0] ? cap(gen[0].nombre) : '—', sub: `${gen.length} genéricas · la mayor concentra ${P(pct(gen[0]?.pim, P_.total.pim))} del PIM`, color: 'var(--p)',
          detalle: () => `<table class="pd-tbl">${head}${gen.map(f => fila(f.nombre, f)).join('')}</table>` },
        { id: 'pca', icono: '🎯', titulo: 'PCA · techo de compromisos', valor: `${FM(pcaA - pcaC)} libre`, sub: `asignado ${F(pcaA)} · certificado ${P(pct(pcaC, pcaA))}`, color: 'var(--teal)', medidor: pct(pcaC, pcaA),
          detalle: () => `<table class="pd-tbl"><tr><th>Fuente</th><th>Genérica</th><th>PCA asignada</th><th>Certificado</th><th>Comprometido</th><th>Libre</th></tr>${pca.sort((a, c) => c.asignado - a.asignado).map(p => `<tr><td style="white-space:normal">${p.fuente_n}</td><td style="white-space:normal">${p.generica_n}</td><td>${F(p.asignado)}</td><td>${F(p.certificado)}</td><td>${F(p.comprometido)}</td><td>${F(p.asignado - p.certificado)}</td></tr>`).join('')}</table>` },
        { id: 'mods', icono: '🔁', titulo: 'Modificaciones presupuestales', valor: `${N(mods.length)} notas`, sub: `${F(cred)} movidos entre metas · última ${mods[0]?.fecha || ''}`, color: '#5E35B1',
          detalle: () => `<table class="pd-tbl"><tr><th>Nota</th><th>Fecha</th><th>Tipo</th><th>Documento</th><th>Crédito (a)</th><th>Anulación (de)</th><th>Metas</th></tr>${mods.slice(0, 150).map(m => `<tr><td>${+m.nota}</td><td>${m.fecha || ''}</td><td style="white-space:normal">${m.tipo_n}</td><td style="white-space:normal;font-size:10.5px">${m.doc || ''}${m.notas && m.notas !== 'CREDITOS Y ANULACIONES' ? '<br>' + m.notas : ''}</td><td>${F(m.credito)}</td><td>${F(m.anulacion)}</td><td style="font-size:10.5px;white-space:normal">${m.metas.map(mlabel).join(', ')}</td></tr>`).join('')}</table>` }
      ]);
    } else if (tabE === 'ing') {
      const fts = Object.values(I.fuentes).filter(f => f.pim || f.recaudado).sort((a, c) => c.recaudado - a.recaudado); const meses = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12'];
      const cl = I.clasificadores.filter(c => c.pim || c.recaudado);
      const mesTot = meses.map(m => fts.reduce((s, f) => s + (f.mensual[m] || 0), 0)), mx = Math.max(...mesTot, 1);
      paneles(b, [
        { id: 'if', icono: '💰', titulo: 'Ingresos por fuente', valor: FM(I.total.recaudado), sub: `recaudado de un PIM de ${F(I.total.pim)} · ${fts.length} fuentes`, color: 'var(--teal)', medidor: pct(I.total.recaudado, I.total.pim),
          detalle: () => `<table class="pd-tbl"><tr><th>Fuente</th><th>PIA</th><th>PIM</th><th>Recaudado</th><th>Avance</th>${meses.map(m => `<th>${MES[+m - 1]}</th>`).join('')}</tr>${fts.map(f => `<tr><td style="white-space:normal">${f.nombre}</td><td>${F(f.pia)}</td><td>${F(f.pim)}</td><td><b>${F(f.recaudado)}</b></td><td>${f.pim ? P(pct(f.recaudado, f.pim)) : '—'}</td>${meses.map(m => `<td style="font-size:10px">${f.mensual[m] ? M(f.mensual[m]) : ''}</td>`).join('')}</tr>`).join('')}<tr><td><b>Total</b></td><td>${F(I.total.pia)}</td><td>${F(I.total.pim)}</td><td><b>${F(I.total.recaudado)}</b></td><td>${P(pct(I.total.recaudado, I.total.pim))}</td><td colspan="12" class="mutx" style="text-align:left;font-size:10px">mensual en S/ millones</td></tr></table>` },
        { id: 'im', icono: '📆', titulo: 'Ritmo mensual de recaudación', valor: `${MES[mesTot.indexOf(mx)]} el mejor mes`, sub: `${F(mx)} · promedio ${F(mesTot.filter(Boolean).reduce((s, v) => s + v, 0) / (mesTot.filter(Boolean).length || 1))} en los meses con registro`, color: 'var(--p2)',
          detalle: () => `<div style="display:flex;align-items:flex-end;gap:6px;height:120px;padding:8px 4px 0">${mesTot.map((v, i) => `<div style="flex:1;text-align:center;font-size:10px;color:var(--ink2)"><div style="height:${Math.round(90 * v / mx)}px;background:var(--p2);border-radius:4px 4px 0 0;margin:0 4px"></div>${MES[i]}<br><b>${v ? M(v) : ''}</b></div>`).join('')}</div><p class="mutx" style="font-size:10.5px;margin:4px 0 0">S/ millones · todas las fuentes</p>` },
        { id: 'ir', icono: '🧾', titulo: 'Por rubro de ingreso', valor: cl[0] ? cap(cl[0].nombre) : '—', sub: `${cl.length} rubros · el principal recauda ${P(pct(cl[0]?.recaudado, I.total.recaudado))} del total`, color: 'var(--gold)',
          detalle: () => `<table class="pd-tbl"><tr><th>Clasificador</th><th>Concepto</th><th>PIM</th><th>Recaudado</th><th>Avance</th></tr>${cl.slice(0, 80).map(c => `<tr><td>${c.cod}</td><td style="white-space:normal">${c.nombre}</td><td>${F(c.pim)}</td><td>${F(c.recaudado)}</td><td>${c.pim ? P(pct(c.recaudado, c.pim)) : '—'}</td></tr>`).join('')}</table>` }
      ]);
    } else if (tabE === 'pi') {
      Incentivos.render(b, E, META, E._ue.cod, exp => { q = String(+exp); filtroMeta = ''; tabE = 'exp'; render(); });
    } else if (tabE === 'inv') {
      const rows = metasSel().filter(m => hit(nombreMeta(m) + ' ' + m.act_proy + ' ' + m.sec_func)).sort((a, c) => (c.pim || c.comp) - (a.pim || a.comp));
      b.innerHTML = `<table><tr><th>${modoInv ? 'CUI · inversión' : 'Meta'}</th><th>PIM SIAF</th><th>Hoy PIM · Dev · Av. <small>(TE)</small></th><th>Certificado</th><th>Comprometido</th><th>Devengado</th><th>Girado</th><th>Pagado</th><th>Avance</th><th>Exp.</th></tr>${rows.map(m => { const c = LAKE[m.act_proy] || {}; const av = m.pim ? 100 * m.dev / m.pim : null; return `<tr class="l" data-sf="${m.sec_func}"><td><b>${m.act_proy}</b> ${nombreMeta(m)}<br><small class="mutx">sec. func. ${m.sec_func} · meta ${m.meta}${c.cui ? ` · <a class="fc" href="#/cui/${c.cui}">ficha ↗</a>` : ''}</small></td><td>${M(m.pim)}</td><td class="mutx" style="white-space:nowrap">${c.pim ? `${M(c.pim)} · ${M(c.dev)} · <b style="color:var(--${cls(100 * (c.dev || 0) / c.pim)})">${P(100 * (c.dev || 0) / c.pim)}</b>${(c.dev || 0) - (m.dev || 0) > 50000 ? ` <span style="color:var(--ok)">▲${M((c.dev || 0) - (m.dev || 0))}</span>` : ''}` : '—'}</td><td>${M(m.cert)}</td><td>${M(m.comp)}</td><td>${M(m.dev)}</td><td>${M(m.gir)}</td><td>${M(m.pag)}</td><td>${av != null ? P(av) : '—'}</td><td>${m.n_exp}</td></tr>`; }).join('')}</table><p class="mutx" style="font-size:11px;padding:6px 8px">S/ millones · PIM SIAF al ${E.corte}; Hoy = Transparencia Económica al ${R.corte} (PIM · devengado · avance; ▲ = devengado nuevo desde el backup SIAF). Clic en una fila para ver sus expedientes.</p>`;
      b.querySelectorAll('tr.l').forEach(tr => tr.onclick = e => { if (e.target.closest('a')) return; filtroMeta = tr.dataset.sf; tabE = 'exp'; render(); });
    } else if (tabE === 'exp') {
      const rows = E.expedientes.filter(e => (!filtroMeta || e.metas.includes(filtroMeta)) && (modoInv ? e.metas.some(s => META[s]?.es_inv) : true) && hit(e.glosa + ' ' + e.proveedor + ' ' + e.exp + ' ' + e.fases.map(f => f.num).join(' ')));
      b.innerHTML = `${filtroMeta && META[filtroMeta] ? `<div class="pd-lbl" style="margin:8px">${META[filtroMeta].es_inv ? 'CUI ' + META[filtroMeta].act_proy : 'Meta ' + META[filtroMeta].meta} · ${nombreMeta(META[filtroMeta])}</div>` : ''}<table><tr><th>Expediente</th><th>Proveedor</th><th>Glosa</th><th>Comprom.</th><th>Deveng.</th><th>Girado</th><th>Pagado</th><th>Última fase</th></tr>${rows.slice(0, 400).map(e => `<tr class="l" data-e="${e.exp}"><td><b>${+e.exp}</b><br><small class="mutx">${e.fecha_ing || ''}</small></td><td style="white-space:normal;min-width:120px;font-size:11px">${e.proveedor || (e.ruc ? 'RUC ' + e.ruc : '—')}</td><td style="white-space:normal;min-width:260px;font-size:11px">${(e.glosa || '').slice(0, 160)}</td><td>${F(e.tot.C)}</td><td>${F(e.tot.D)}</td><td>${F(e.tot.G)}</td><td>${F(e.tot.P)}</td><td>${e.ult_fase ? `<span class="tag ${e.ult_fase === 'P' ? 'ok' : e.ult_fase === 'C' ? 'warn' : 'p'}" style="${e.ult_fase === 'D' || e.ult_fase === 'G' ? 'background:#E3F0FB;color:var(--p2)' : ''}">${FASE[e.ult_fase]}</span><br><small class="mutx">${e.ult_fecha || ''}</small>` : '—'}</td></tr><tr class="det" data-d="${e.exp}" hidden><td colspan="8" style="white-space:normal;background:var(--sup2)"></td></tr>`).join('')}</table><p class="mutx" style="font-size:11px;padding:6px 8px">${rows.length} expedientes${rows.length > 400 ? ' (se muestran 400; afina la búsqueda)' : ''}. Clic para ver la cadena de fases con documentos.</p>`;
      b.querySelectorAll('tr.l').forEach(tr => tr.onclick = () => { const d = b.querySelector(`tr.det[data-d="${tr.dataset.e}"]`); if (!d.hidden) { d.hidden = true; return; } const e = E.expedientes.find(x => x.exp === tr.dataset.e); d.firstChild.innerHTML = cadena(e); d.hidden = false; });
    } else if (tabE === 'al') {
      const f = r => !modoInv || r.metas.some(s => META[s]?.es_inv);
      const tabla = (rows, k) => rows.length ? `<table><tr><th>${k}</th><th>Proveedor</th><th>Glosa</th><th>Monto</th><th>Días</th><th>Metas</th></tr>${rows.slice(0, 60).map(x => `<tr class="l" data-e="${x.exp || ''}" style="cursor:pointer"><td><b>${+(x.exp || x.cert)}</b></td><td style="white-space:normal;font-size:11px">${x.prov || '—'}</td><td style="white-space:normal;min-width:240px;font-size:11px">${(x.glosa || '').slice(0, 140)}</td><td>${F(x.monto)}</td><td><span class="tag ${x.dias > 90 ? 'bad' : x.dias > 45 ? 'warn' : 'ok'}">${x.dias}</span></td><td style="font-size:11px">${x.metas.map(mlabel).join(', ')}</td></tr>`).join('')}</table>` : '<p class="mutx" style="padding:4px 8px;font-size:11px">Sin casos.</p>';
      const def = [['dev_sin_girar', '💸', 'Proveedores sin cobrar', 'la entidad ya reconoció la deuda (devengado) y no ha girado en más de 15 días', 'var(--bad)', '#FDECEC', 'Expediente'], ['comp_sin_devengar', '⏳', 'Contratos sin avanzar', 'contrato u orden firmada (comprometido) sin recepción del bien o servicio en más de 45 días', 'var(--warn)', '#FFF4E0', 'Expediente'], ['cert_sin_comp', '🔒', 'Presupuesto reservado sin usar', 'certificaciones con más de 60 días sin compromiso: dinero inmovilizado', 'var(--p)', '#E8F1FB', 'Certificación']];
      paneles(b, def.map(([k, ic, t, d, col, bg, kk]) => { const rows = A[k].filter(f), mx = rows.reduce((s, x) => Math.max(s, x.dias || 0), 0); return { id: k, icono: ic, titulo: t, valor: `${N(rows.length)} casos · ${FM(rows.reduce((s, x) => s + (x.monto || 0), 0))}`, sub: `${d}${mx ? ` · el más antiguo lleva ${mx} días` : ''}`, color: rows.length ? col : 'var(--ok)', bg: rows.length ? bg : '#EAF5EA', detalle: () => tabla(rows, kk) }; }), 'Clic en un caso para abrir su expediente.');
      b.querySelectorAll('tr.l[data-e]').forEach(tr => tr.onclick = () => { if (!tr.dataset.e) return; q = String(+tr.dataset.e); filtroMeta = ''; tabE = 'exp'; render(); });
    } else if (tabE === 'prov') {
      const rows = E.proveedores.filter(p => hit(p.nombre + ' ' + p.ruc)), pend = rows.filter(p => p.dev - p.gir > 1), tot = rows.reduce((s, p) => s + p.dev, 0);
      const tabla = rs => `<table><tr><th>RUC</th><th>Proveedor</th><th>Comprometido</th><th>Devengado</th><th>Girado</th><th>Pendiente de giro</th><th>Exp.</th></tr>${rs.slice(0, 300).map(p => `<tr class="l" data-r="${p.ruc}" style="cursor:pointer"><td>${p.ruc}</td><td style="white-space:normal">${p.nombre || '—'}</td><td>${F(p.comp)}</td><td>${F(p.dev)}</td><td>${F(p.gir)}</td><td>${F(Math.max(0, p.dev - p.gir))}</td><td>${p.n}</td></tr>`).join('')}</table>`;
      paneles(b, [
        { id: 'pend', icono: '💸', titulo: 'Proveedores con pagos pendientes', valor: `${N(pend.length)} · ${FM(pend.reduce((s, p) => s + p.dev - p.gir, 0))} por girar`, sub: 'devengado y aún no girado: son los que están llamando a tesorería', color: pend.length ? 'var(--bad)' : 'var(--ok)', bg: pend.length ? '#FDECEC' : '#EAF5EA', detalle: () => tabla(pend.sort((a, c) => (c.dev - c.gir) - (a.dev - a.gir))) },
        { id: 'top', icono: '🏆', titulo: 'Los 10 proveedores principales', valor: FM(rows.slice(0, 10).reduce((s, p) => s + p.dev, 0)), sub: `${P(pct(rows.slice(0, 10).reduce((s, p) => s + p.dev, 0), tot))} de todo lo devengado a proveedores`, color: 'var(--p2)', detalle: () => tabla(rows.slice(0, 10)) },
        { id: 'todos', icono: '📇', titulo: 'Todos los proveedores', valor: N(rows.length), sub: `devengado total ${F(tot)} · clic para ver el directorio completo`, color: 'var(--p)', detalle: () => tabla(rows) }
      ], 'Clic en un proveedor para ver sus expedientes.');
      b.querySelectorAll('tr.l').forEach(tr => tr.onclick = () => { q = tr.dataset.r; tabE = 'exp'; filtroMeta = ''; render(); });
    } else if (tabE === 'cert') {
      const rows = Object.entries(E.certificaciones).filter(([k, c]) => (!modoInv || c.metas.some(s => META[s]?.es_inv)) && hit(c.glosa + ' ' + c.prov + ' ' + k)).sort((a, c) => c[1].monto - a[1].monto);
      const tot = rows.reduce((s, [, c]) => s + c.monto, 0), com = rows.reduce((s, [, c]) => s + c.comp_anual, 0), libres = rows.filter(([, c]) => c.monto - c.comp_anual > 1);
      const tabla = rs => `<table><tr><th>Certificación</th><th>Fecha</th><th>Documento</th><th>Proveedor</th><th>Glosa</th><th>Certificado</th><th>Comprometido</th><th>Por comprometer</th><th>Metas</th></tr>${rs.slice(0, 400).map(([k, c]) => `<tr><td><b>${+k}</b></td><td>${c.fecha || ''}</td><td style="font-size:11px">${c.doc}</td><td style="white-space:normal;font-size:11px">${c.prov || ''}</td><td style="white-space:normal;min-width:240px;font-size:11px">${(c.glosa || '').slice(0, 140)}</td><td>${F(c.monto)}</td><td>${F(c.comp_anual)}</td><td>${F(Math.max(0, c.monto - c.comp_anual))}</td><td style="font-size:11px">${c.metas.map(mlabel).join(', ')}</td></tr>`).join('')}</table>`;
      paneles(b, [
        { id: 'c', icono: '📜', titulo: 'Certificaciones emitidas', valor: `${N(rows.length)} · ${FM(tot)}`, sub: `comprometido ${P(pct(com, tot))} de lo certificado`, color: 'var(--p2)', medidor: pct(com, tot), detalle: () => tabla(rows) },
        { id: 'l', icono: '🪙', titulo: 'Certificado sin comprometer', valor: FM(tot - com), sub: `${N(libres.length)} certificaciones con saldo: presupuesto reservado que aún no tiene contrato`, color: libres.length ? 'var(--warn)' : 'var(--ok)', bg: libres.length ? '#FFF4E0' : '#EAF5EA', detalle: () => tabla(libres.sort((a, c) => (c[1].monto - c[1].comp_anual) - (a[1].monto - a[1].comp_anual))) }
      ]);
    }
  }
  function cadena(e) {
    const gasto = e.fases.filter(f => f.ciclo === 'G');
    return `<div style="padding:8px 4px"><div class="pd-row" style="margin-bottom:8px"><b>Glosa</b><span style="font-weight:500">${e.glosa || '—'}</span></div>
     <table class="pd-tbl"><tr><th>Fecha</th><th>Fase</th><th>Documento</th><th>Monto</th><th>Fuente</th><th>Meta · clasificador</th><th>Pago / beneficiario</th></tr>${gasto.map(f => `<tr><td>${f.fecha || ''}</td><td><b>${FASE[f.fase] || f.fase}</b> <small class="mutx">${f.sec}-${f.corr}</small>${f.cert ? `<br><small class="mutx">cert. ${+f.cert}</small>` : ''}</td><td style="white-space:normal">${f.doc_n || f.doc} <b>${f.num}</b></td><td>${F(f.monto)}</td><td style="font-size:10.5px">${E.fuentes[f.fuente] || f.fuente || ''}</td><td style="white-space:normal;font-size:10.5px">${f.metas.map(m => `${META[m.sec_func] ? (META[m.sec_func].es_inv ? META[m.sec_func].act_proy : 'meta ' + META[m.sec_func].meta) : m.sec_func} · ${E.clasif[m.clasif]?.cod || ''} ${E.clasif[m.clasif]?.nombre || ''} (${F(m.monto)})`).join('<br>')}</td><td style="white-space:normal;font-size:10.5px">${f.docs.map(d => `${d.nombre || ''} ${d.num ? '· ' + d.num : ''} ${d.pago ? '· pagado ' + d.pago : ''}`).join('<br>') || (f.prov || '')}</td></tr>`).join('')}</table></div>`;
  }
  function atras() {
    if (!E) return false;
    if (tabE === 'pi' && window.Incentivos?.atras?.()) return true;
    if (abiertos[tabE]) { abiertos[tabE] = null; cuerpo(); return true; }
    if (pila.length < 2) return false;
    pila.pop(); [tabE, filtroMeta, modoInv, q] = pila[pila.length - 1].split('|'); modoInv = modoInv === 'true'; restaurando = true; render(); return true;
  }
  window.Entidad = { atras, abrir: async (ue) => { if (E && (!ue || E.ue === ue)) { render(); return; } await login(); if (ue && $('ent-ue')) $('ent-ue').value = ue; } };
})();
